
The Written Word
---------------------------------------------------------------------
					           thewrittenword.com


			Open Source Made Easy


Please contact us at the following email address with any questions or
problems:
	%E

Files with the extension .tar.Z are compressed tar archives. The UNIX
compress(1) program can be used to uncompress the archive and tar(1)
to extract the contents of the archive.
